### ISSUE TITLE
Consider converting jupyter notebooks to jupytext compatible python files

### ISSUE THREAD

**Issue by seanybaggins** [colbrydi/MatrixAlgebra#4]
There are a few advantages to adding [jupytext](https://jupytext.readthedocs.io/en/latest/)...
- Its easy to implement
- You get better diffs within github
- You don't loose any jupyter notebook functionality. You don't notice that you are working with a jupytext python file when in the jupyter notebook user interface.
- You can use an editor other than the standard web interface.

**Implementation**
In `environment.yml`. Add the following,
```yml
channels:
  - defaults
  - conda-forge
# ...

dependencies:
#...
  - pip:
    - jupyter-book
```
